packages:
  - .

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@stellar/stellar-sdk'
  - bigint-buffer
  - blake-hash
  - blake-hashx1
  - bufferutil
  - protobufjs
  - tiny-secp256k1
  - usb
  - utf-8-validate
